# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "polaris-k8s"
version = "0.0.1"
requires-python = ">=3.12,<3.15"

dependencies = [
  "ops>=3.7",
  "PyYAML>=6.0.0",
  "apache-polaris (>=1.6.0,<2.0.0)",
  "charmlibs-pathops (>=1.3.0)",
  "data-platform-helpers (>1.0.1)",
  "dpcharmlibs-interfaces (>=1.1.0)",
  "object-storage-charmlib (>=1.0.0,<2.0.0)",
]

[dependency-groups]
charm-libs = [
  "cosl (>=1.10.2,<2.0.0)",
  "pydantic (>=2,<3)",
  "pyyaml (>=6.0.3,<7.0.0)",
]
format = [
  "ruff>=0.15.0",
]
lint = [
  "codespell>=2.4.0",
  "ruff>=0.15.0",
  "zuban>=0.9.0",
  "types-boto3[essentials] (>=1.43.50,<2.0.0)",
]
unit = [
  "coverage[toml]>=7.0.0",
  "ops[testing]>=3.7",
  "pytest>=9.0.0",
]
integration = [
  "jubilant>=1.8.0",
  "pytest>=9.0.0",
  "python-dotenv (>=1.2.2,<2.0.0)",
  "boto3 (>=1.43.3,<1.43.47)",
  "pyiceberg[pyarrow,s3fs] (>=0.10.0,<1.0.0)",
  "tenacity (>=9.1.4,<10.0.0)",
  "httpx2 (>=2.7.0,<3.0.0)",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "9.0"
log_cli_level = "INFO"

[tool.ruff]
line-length = 99
lint.select = ["E", "W", "F", "C", "N", "D", "I001"]
lint.ignore = [
  "D105",
  "D107",
  "D203",
  "D204",
  "D213",
  "D215",
  "D400",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
]
lint.per-file-ignores = { "src/charm.py" = ["E402"], "tests/*" = ["D100", "D101", "D102", "D103", "D104"], "src/*/__init__.py" = ["D104"] }
extend-exclude = ["__pycache__", "*.egg_info", "lib"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.codespell]
skip = "build,lib,venv,icon.svg,.tox,.git,.mypy_cache,.ruff_cache,.coverage,poetry.lock"

[tool.mypy]
exclude = [
  "lib",
]
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
  "charms.data_platform_libs.*",
]
ignore_missing_imports = true

[tool.pyright]
include = ["src"]
extraPaths = ["./lib", "src"]
pythonVersion = "3.12"
pythonPlatform = "All"
typeCheckingMode = "basic"

[tool.poetry]
package-mode = false
