{
 "title": "Apache Polaris Metrics",
 "tags": [
  "quarkus",
  "juju",
  "cos"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheusds", "label": "Data Source", "query": "prometheus" },
   { "name": "juju_model", "label": "Juju model", "query": "label_values(up, juju_model)" },
   {
    "name": "juju_model_uuid",
    "label": "Juju model UUID",
    "query": "label_values(up, juju_model_uuid)"
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": "label_values(up{juju_model=~\"$juju_model\"}, juju_application)"
   },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": "label_values(up{juju_model=~\"$juju_model\", juju_application=~\"$juju_application\"}, juju_unit)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{juju_model=~\"$juju_model\", juju_charm=~\"polaris-k8s\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active HTTP Requests & Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\", juju_unit=~\"$juju_unit\", server_port=\"8181\"}) by (juju_unit)",
     "legendFormat": "Requests {{juju_unit}}"
    },
    {
     "expr": "sum(http_server_active_connections{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\", juju_unit=~\"$juju_unit\", server_port=\"8181\"}) by (juju_unit)",
     "legendFormat": "Connections {{juju_unit}}"
    }
   ]
  },
  {
   "title": "HTTP Network Throughput & Response Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_bytes_written_sum{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\", juju_unit=~\"$juju_unit\", server_port=\"8181\"}[5m])) by (juju_unit)",
     "legendFormat": "Egress {{juju_unit}}"
    },
    {
     "expr": "sum(rate(http_server_bytes_read_sum{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\", juju_unit=~\"$juju_unit\", server_port=\"8181\"}[5m])) by (juju_unit)",
     "legendFormat": "Ingress {{juju_unit}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", juju_model=~\"$juju_model\", juju_charm=\"polaris-k8s\"}) by (juju_unit)",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  }
 ]
}